// src/services/airportDataService.js
// Loads airports.json (pre-built from airports-extended.dat) for DAN/DAC commands.
// airports.json is generated by: node scripts/build-airports-json.mjs

/**
 * Each entry in airports.json:
 * { city: string, country: string, airports: [{ iata: string, name: string }] }
 */
class AirportDataService {
  constructor() {
    this.initialized = false;
    this._loading = null;   // Promise guard — prevents double-load
    this.cityList = [];     // Array from airports.json (sorted by city)
    this.iataIndex = {};     // iata → { city, country, name }
    this.cityIndex = {};     // CITY_UPPER → [entries]

    // Minimal fallback used if JSON cannot be fetched
    this.fallback = [
      { city: 'Buenos Aires', country: 'Argentina', airports: [{ iata: 'EZE', name: 'Ministro Pistarini International Airport' }, { iata: 'AEP', name: 'Jorge Newbery Airfield' }] },
      { city: 'Madrid', country: 'Spain', airports: [{ iata: 'MAD', name: 'Adolfo Suárez Madrid–Barajas Airport' }] },
      { city: 'London', country: 'United Kingdom', airports: [{ iata: 'LHR', name: 'London Heathrow Airport' }, { iata: 'LGW', name: 'London Gatwick Airport' }, { iata: 'STN', name: 'London Stansted Airport' }] },
      { city: 'Paris', country: 'France', airports: [{ iata: 'CDG', name: 'Charles de Gaulle Airport' }, { iata: 'ORY', name: 'Paris Orly Airport' }] },
      { city: 'New York', country: 'United States', airports: [{ iata: 'JFK', name: 'John F. Kennedy International Airport' }, { iata: 'EWR', name: 'Newark Liberty International Airport' }] },
      { city: 'Miami', country: 'United States', airports: [{ iata: 'MIA', name: 'Miami International Airport' }] },
      { city: 'Frankfurt', country: 'Germany', airports: [{ iata: 'FRA', name: 'Frankfurt am Main Airport' }] },
      { city: 'Rome', country: 'Italy', airports: [{ iata: 'FCO', name: 'Leonardo da Vinci International Airport' }] },
      { city: 'Amsterdam', country: 'Netherlands', airports: [{ iata: 'AMS', name: 'Amsterdam Airport Schiphol' }] },
      { city: 'Dubai', country: 'United Arab Emirates', airports: [{ iata: 'DXB', name: 'Dubai International Airport' }] },
    ];
  }

  // ── Public API ─────────────────────────────────────────────────────────────

  /** Initialize (idempotent, safe to call multiple times) */
  async initialize() {
    if (this.initialized) return true;
    if (this._loading) return this._loading;

    this._loading = this._load();
    return this._loading;
  }

  /** Search cities by partial name — used by DAN */
  searchCitiesByName(query) {
    if (!this.initialized) { this.initialize(); return this._fallbackSearch(query); }
    const q = query.toUpperCase().trim();
    const results = [];
    for (const key of Object.keys(this.cityIndex)) {
      if (key.includes(q)) {
        results.push(...this.cityIndex[key]);
      }
    }
    return results.map(e => this._toServiceFormat(e));
  }

  /** Get city/airport info by IATA code — used by DAC */
  getCityByCode(iata) {
    if (!this.initialized) { this.initialize(); return null; }
    const entry = this.iataIndex[iata.toUpperCase()];
    if (!entry) return null;
    return this._toServiceFormat(entry.group);
  }

  /** Get airport by IATA — for internal use */
  getAirportByCode(iata) {
    if (!this.initialized) { this.initialize(); return null; }
    return this.iataIndex[iata.toUpperCase()] || null;
  }

  getInitializedStatus() { return this.initialized; }

  // ── Private ────────────────────────────────────────────────────────────────

  async _load() {
    try {
      const res = await fetch('/data/airports.json');
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      this._buildIndexes(data);
      this.initialized = true;
      console.log(`[AirportDataService] Loaded ${this.cityList.length} city groups`);
      return true;
    } catch (err) {
      console.warn('[AirportDataService] Failed to load airports.json, using fallback:', err.message);
      this._buildIndexes(this.fallback);
      this.initialized = true;
      return false;
    }
  }

  _buildIndexes(cityList) {
    this.cityList = cityList;
    this.iataIndex = {};
    this.cityIndex = {};

    for (const group of cityList) {
      const cityUpper = group.city.toUpperCase();

      // City index — supports partial match
      if (!this.cityIndex[cityUpper]) this.cityIndex[cityUpper] = [];
      this.cityIndex[cityUpper].push(group);

      // IATA index — exact match
      for (const airport of group.airports) {
        this.iataIndex[airport.iata] = { ...airport, group };
      }
    }
  }

  /** Convert internal format → format expected by city.js */
  _toServiceFormat(group) {
    return {
      code: group.airports[0]?.iata || '',
      name: group.city,
      name_uppercase: group.city.toUpperCase(),
      country: group.country,
      countryCode: this._isoCode(group.country),
      airports: group.airports.map(a => ({
        code: a.iata,
        name: a.name,
        distance: '0K',
      })),
    };
  }

  _fallbackSearch(query) {
    const q = query.toUpperCase();
    return this.fallback
      .filter(g => g.city.toUpperCase().includes(q))
      .map(g => this._toServiceFormat(g));
  }

  /** Best-effort country name → ISO-2 code */
  _isoCode(country) {
    const map = {
      'Argentina': 'AR', 'Spain': 'ES', 'United Kingdom': 'GB',
      'France': 'FR', 'Germany': 'DE', 'Italy': 'IT',
      'Netherlands': 'NL', 'United States': 'US', 'Brazil': 'BR',
      'Chile': 'CL', 'Colombia': 'CO', 'Peru': 'PE',
      'Mexico': 'MX', 'Australia': 'AU', 'Japan': 'JP',
      'China': 'CN', 'Canada': 'CA', 'Portugal': 'PT',
      'United Arab Emirates': 'AE', 'Qatar': 'QA', 'Turkey': 'TR',
      'South Africa': 'ZA', 'India': 'IN', 'Thailand': 'TH',
      'Singapore': 'SG', 'Hong Kong': 'HK', 'Uruguay': 'UY',
      'Paraguay': 'PY', 'Bolivia': 'BO', 'Ecuador': 'EC',
      'Venezuela': 'VE', 'Panama': 'PA', 'Costa Rica': 'CR',
      'Cuba': 'CU', 'Dominican Republic': 'DO', 'Greece': 'GR',
      'Switzerland': 'CH', 'Austria': 'AT', 'Belgium': 'BE',
      'Sweden': 'SE', 'Norway': 'NO', 'Denmark': 'DK',
      'Finland': 'FI', 'Poland': 'PL', 'Russia': 'RU',
      'Israel': 'IL', 'Saudi Arabia': 'SA', 'Egypt': 'EG',
      'Morocco': 'MA', 'South Korea': 'KR', 'Indonesia': 'ID',
      'Malaysia': 'MY', 'New Zealand': 'NZ', 'Ireland': 'IE',
    };
    return map[country] || country.slice(0, 2).toUpperCase();
  }
}

const airportDataService = new AirportDataService();
export default airportDataService;