// src/services/airportDataService.js
// Loads airports.json (pre-built from airports-extended.dat) for DAN/DAC commands.
// airports.json is generated by: node scripts/build-airports-json.mjs

/**
 * Each entry in airports.json:
 * { city: string, country: string, airports: [{ iata: string, name: string }] }
 */

/**
 * Multi-airport city codes (Amadeus city codes that don't exist as individual airport IATA codes).
 * Maps cityCode → { city: exact city name in airports.json, country: exact country name }
 * Used by getCityByCode() so that DAC BUE finds Buenos Aires instead of partial-matching "Bue*".
 */
const CITY_CODE_MAP = {
  // South America
  'BUE': { city: 'Buenos Aires', country: 'Argentina' },
  'RIO': { city: 'Rio de Janeiro', country: 'Brazil' },
  'SAO': { city: 'Sao Paulo',     country: 'Brazil' },
  // North America
  'NYC': { city: 'New York',      country: 'United States' },
  'WAS': { city: 'Washington',    country: 'United States' },
  'CHI': { city: 'Chicago',       country: 'United States' },
  'YTO': { city: 'Toronto',       country: 'Canada' },
  'YMQ': { city: 'Montreal',      country: 'Canada' },
  // Europe
  'LON': { city: 'London',        country: 'United Kingdom' },
  'PAR': { city: 'Paris',         country: 'France' },
  'ROM': { city: 'Rome',          country: 'Italy' },
  'MIL': { city: 'Milan',         country: 'Italy' },
  'MOW': { city: 'Moscow',        country: 'Russia' },
  'STO': { city: 'Stockholm',     country: 'Sweden' },
  // Asia / Middle East
  'TYO': { city: 'Tokyo',         country: 'Japan' },
  'OSA': { city: 'Osaka',         country: 'Japan' },
  'BJS': { city: 'Beijing',       country: 'China' },
  'SHA': { city: 'Shanghai',      country: 'China' },
  'SEL': { city: 'Seoul',         country: 'South Korea' },
};

class AirportDataService {
  constructor() {
    this.initialized = false;
    this._loading = null;   // Promise guard — prevents double-load
    this.cityList = [];     // Array from airports.json (sorted by city)
    this.iataIndex = {};     // iata → { city, country, name }
    this.cityIndex = {};     // CITY_UPPER → [entries]

    // Minimal fallback used if JSON cannot be fetched
    this.fallback = [
      { city: 'Buenos Aires', country: 'Argentina', airports: [{ iata: 'EZE', name: 'Ministro Pistarini International Airport' }, { iata: 'AEP', name: 'Jorge Newbery Airfield' }] },
      { city: 'Madrid', country: 'Spain', airports: [{ iata: 'MAD', name: 'Adolfo Suárez Madrid–Barajas Airport' }] },
      { city: 'London', country: 'United Kingdom', airports: [{ iata: 'LHR', name: 'London Heathrow Airport' }, { iata: 'LGW', name: 'London Gatwick Airport' }, { iata: 'STN', name: 'London Stansted Airport' }] },
      { city: 'Paris', country: 'France', airports: [{ iata: 'CDG', name: 'Charles de Gaulle Airport' }, { iata: 'ORY', name: 'Paris Orly Airport' }] },
      { city: 'New York', country: 'United States', airports: [{ iata: 'JFK', name: 'John F. Kennedy International Airport' }, { iata: 'EWR', name: 'Newark Liberty International Airport' }] },
      { city: 'Miami', country: 'United States', airports: [{ iata: 'MIA', name: 'Miami International Airport' }] },
      { city: 'Frankfurt', country: 'Germany', airports: [{ iata: 'FRA', name: 'Frankfurt am Main Airport' }] },
      { city: 'Rome', country: 'Italy', airports: [{ iata: 'FCO', name: 'Leonardo da Vinci International Airport' }] },
      { city: 'Amsterdam', country: 'Netherlands', airports: [{ iata: 'AMS', name: 'Amsterdam Airport Schiphol' }] },
      { city: 'Dubai', country: 'United Arab Emirates', airports: [{ iata: 'DXB', name: 'Dubai International Airport' }] },
    ];
  }

  // ── Public API ─────────────────────────────────────────────────────────────

  /** Initialize (idempotent, safe to call multiple times) */
  async initialize() {
    if (this.initialized) return true;
    if (this._loading) return this._loading;

    this._loading = this._load();
    return this._loading;
  }

  /** Search cities by partial name — used by DAN */
  searchCitiesByName(query) {
    if (!this.initialized) { this.initialize(); return this._fallbackSearch(query); }
    const q = query.toUpperCase().trim();
    const results = [];
    for (const key of Object.keys(this.cityIndex)) {
      if (key.includes(q)) {
        results.push(...this.cityIndex[key]);
      }
    }
    return results.map(e => this._toServiceFormat(e));
  }

  /** Search airports by partial name — used by DAC */
  searchByAirportName(query) {
    if (!this.initialized) { this.initialize(); return []; }
    const q = query.toUpperCase().trim();
    const results = [];

    // Iterate through all city groups
    for (const group of this.cityList) {
      // Check if any airport in this group matches
      const hasMatch = group.airports.some(a => a.name.toUpperCase().includes(q));
      if (hasMatch) {
        results.push(this._toServiceFormat(group));
      }
    }
    return results;
  }

  /** Get city/airport info by IATA code — used by DAC.
   *  Handles both airport codes (EZE, MAD) and multi-airport city codes (BUE, NYC, LON).
   */
  getCityByCode(iata) {
    if (!this.initialized) { this.initialize(); return null; }
    const code = iata.toUpperCase();

    // 1. Exact airport IATA code (e.g. EZE, MAD, CDG)
    const entry = this.iataIndex[code];
    if (entry) return this._toServiceFormat(entry.group, code);

    // 2. Multi-airport city code (e.g. BUE → Buenos Aires/Argentina)
    const mapping = CITY_CODE_MAP[code];
    if (mapping) {
      const cityUpper = mapping.city.toUpperCase();
      const groups = this.cityIndex[cityUpper];
      if (groups) {
        // Prefer the group whose country matches exactly
        const match = groups.find(g => g.country === mapping.country) || groups[0];
        return this._toServiceFormat(match, code);
      }
    }

    return null;
  }

  /** Get airport by IATA — for internal use */
  getAirportByCode(iata) {
    if (!this.initialized) { this.initialize(); return null; }
    return this.iataIndex[iata.toUpperCase()] || null;
  }

  getInitializedStatus() { return this.initialized; }

  // ── Private ────────────────────────────────────────────────────────────────

  async _load() {
    try {
      const res = await fetch('/data/airports.json');
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data = await res.json();
      this._buildIndexes(data);
      this.initialized = true;
      console.log(`[AirportDataService] Loaded ${this.cityList.length} city groups`);
      return true;
    } catch (err) {
      console.warn('[AirportDataService] Failed to load airports.json, using fallback:', err.message);
      this._buildIndexes(this.fallback);
      this.initialized = true;
      return false;
    }
  }

  _buildIndexes(cityList) {
    this.cityList = cityList;
    this.iataIndex = {};
    this.cityIndex = {};

    for (const group of cityList) {
      const cityUpper = group.city.toUpperCase();

      // City index — supports partial match
      if (!this.cityIndex[cityUpper]) this.cityIndex[cityUpper] = [];
      this.cityIndex[cityUpper].push(group);

      // IATA index — exact match
      for (const airport of group.airports) {
        this.iataIndex[airport.iata] = { ...airport, group };
      }
    }
  }

  /** Convert internal format → format expected by city.js.
   *  @param {object} group   - city group from airports.json
   *  @param {string} [code]  - explicit city/airport code to use (e.g. 'BUE'); falls back to first airport IATA
   */
  _toServiceFormat(group, code) {
    return {
      code: code || group.airports[0]?.iata || '',
      name: group.city,
      name_uppercase: group.city.toUpperCase(),
      country: group.country,
      countryCode: this._isoCode(group.country),
      airports: group.airports.map(a => ({
        code: a.iata,
        name: a.name,
        distance: '0K',
      })),
    };
  }

  _fallbackSearch(query) {
    const q = query.toUpperCase();
    return this.fallback
      .filter(g => g.city.toUpperCase().includes(q))
      .map(g => this._toServiceFormat(g));
  }

  /** Best-effort country name → ISO-2 code */
  _isoCode(country) {
    const map = {
      'Argentina': 'AR', 'Spain': 'ES', 'United Kingdom': 'GB',
      'France': 'FR', 'Germany': 'DE', 'Italy': 'IT',
      'Netherlands': 'NL', 'United States': 'US', 'Brazil': 'BR',
      'Chile': 'CL', 'Colombia': 'CO', 'Peru': 'PE',
      'Mexico': 'MX', 'Australia': 'AU', 'Japan': 'JP',
      'China': 'CN', 'Canada': 'CA', 'Portugal': 'PT',
      'United Arab Emirates': 'AE', 'Qatar': 'QA', 'Turkey': 'TR',
      'South Africa': 'ZA', 'India': 'IN', 'Thailand': 'TH',
      'Singapore': 'SG', 'Hong Kong': 'HK', 'Uruguay': 'UY',
      'Paraguay': 'PY', 'Bolivia': 'BO', 'Ecuador': 'EC',
      'Venezuela': 'VE', 'Panama': 'PA', 'Costa Rica': 'CR',
      'Cuba': 'CU', 'Dominican Republic': 'DO', 'Greece': 'GR',
      'Switzerland': 'CH', 'Austria': 'AT', 'Belgium': 'BE',
      'Sweden': 'SE', 'Norway': 'NO', 'Denmark': 'DK',
      'Finland': 'FI', 'Poland': 'PL', 'Russia': 'RU',
      'Israel': 'IL', 'Saudi Arabia': 'SA', 'Egypt': 'EG',
      'Morocco': 'MA', 'South Korea': 'KR', 'Indonesia': 'ID',
      'Malaysia': 'MY', 'New Zealand': 'NZ', 'Ireland': 'IE',
    };
    return map[country] || country.slice(0, 2).toUpperCase();
  }
}

const airportDataService = new AirportDataService();
export default airportDataService;